//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfluenceAutomator.Library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfluenceAutomator.Library.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        public static string APPLICATION_JSON {
            get {
                return ResourceManager.GetString("APPLICATION_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to exit this application?.
        /// </summary>
        public static string ARE_YOU_SURE_1 {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baseUrl.
        /// </summary>
        public static string BASEURL_KEY {
            get {
                return ResourceManager.GetString("BASEURL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string BASIC {
            get {
                return ResourceManager.GetString("BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /child/page.
        /// </summary>
        public static string CHILDPAGE_PATH {
            get {
                return ResourceManager.GetString("CHILDPAGE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePageUrl.
        /// </summary>
        public static string CREATE_PAGE_URL_KEY {
            get {
                return ResourceManager.GetString("CREATE_PAGE_URL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateSpaceUrl.
        /// </summary>
        public static string CREATE_SPACEURL_KEY {
            get {
                return ResourceManager.GetString("CREATE_SPACEURL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Confirmation.
        /// </summary>
        public static string EXIT_CONFIRMATION {
            get {
                return ResourceManager.GetString("EXIT_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetChildPagesUrl.
        /// </summary>
        public static string GET_CHILDPAGES_URL {
            get {
                return ResourceManager.GetString("GET_CHILDPAGES_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPageByTitleAndKeyUrl.
        /// </summary>
        public static string GET_PAGEBY_TITLE_KEY_URL {
            get {
                return ResourceManager.GetString("GET_PAGEBY_TITLE_KEY_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includePageContent.
        /// </summary>
        public static string INCLUDE_PAGECONTENT_KEY {
            get {
                return ResourceManager.GetString("INCLUDE_PAGECONTENT_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered a invalid credentials..
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        public static string KEY {
            get {
                return ResourceManager.GetString("KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string LOGIN_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentBusinessCaseTitle.
        /// </summary>
        public static string PARENT_BUSINESS_CASE_TITLE_KEY {
            get {
                return ResourceManager.GetString("PARENT_BUSINESS_CASE_TITLE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string PASSWORD_KEY {
            get {
                return ResourceManager.GetString("PASSWORD_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdatePageUrl.
        /// </summary>
        public static string UPDATEPAGE_URL_KEY {
            get {
                return ResourceManager.GetString("UPDATEPAGE_URL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string USERNAME_KEY {
            get {
                return ResourceManager.GetString("USERNAME_KEY", resourceCulture);
            }
        }
    }
}
